### ISSUE TITLE
Support setting client_tags in profile configuration

### ISSUE THREAD

**Issue by Aka-shi** [starburstdata/dbt-trino#111]
### Describe the feature
We plan to use client_tags in Trino to set resource group policies. It would be really helpful if we can set client tags in the trino profile configuration

### Are you interested in contributing this feature?
If someone can help me, where do we set/define profile configuration parameters, I would really like to contribute

**Comment by mdesmet** [comment]
HI @Aka-shi,

that is indeed a very welcome enhancement.

You can have a look at following code:

https://github.com/starburstdata/dbt-trino/blob/a51306ab2d213386cce369d2e05812b0eaa01c9d/dbt/adapters/trino/connections.py#L30-L45

The Credential classes are split per authentication type. Each class is a dataclass and can be extended with the a `client_tags` property. Note that inheritance is not supported for dataclasses if you want to provide a default value.

The tests are located in following file:

https://github.com/starburstdata/dbt-trino/blob/a51306ab2d213386cce369d2e05812b0eaa01c9d/tests/unit/test_adapter.py#L85

Set up your development environment with the [contributing guide](https://github.com/starburstdata/dbt-trino/blob/master/CONTRIBUTING.md).

**Comment by mdesmet** [comment]
@Aka-shi : Let us know how we can help you. We are also on the [slack](https://getdbt.slack.com/channels/db-presto-trino).
