### ISSUE TITLE
failure when enable store_failures with boolean parameter

### ISSUE THREAD

**Issue by bachng2017** [starburstdata/dbt-trino#140]
### Expected behavior

by default, dbt works like this (ref from https://github.com/dbt-labs/dbt-core/pull/1558)
```
When dbt creates a relation in the db, add a special flag to the relation (defaults to False)
When checking a node name match:

if that flag is present and quoting is disabled, do a lowercase compare
otherwise remain case sensitive
```

the default behavior will fail with following case:

when enable store_failures, if the test includes Boolean parameter, dbt will try to save a test model with name __False__. First save will be fine, but second will fail because dbt will compare __False__ model with __false__ model (the one that has been saved)

error will looks like this:
```
06:21:21  Compilation Error in test accepted_values_model____False__0__1 (models/xxx/model.yml)
06:21:21    When searching for a relation, dbt found an approximate match. Instead of guessing
06:21:21    which relation to use, dbt will move on. Please delete "hive"."lab_dbt_xxx"."accepted_values_model____false__0__1", or rename it to be less ambiguous.
06:21:21    Searched for: "hive"."lab_dbt_xxx"."accepted_values_model____False__0__1"   <-- False is in upper case
06:21:21    Found: "hive"."lab_dbt_xxx"."accepted_values_model____false__0__1"
```

### Actual behavior

no error and the test model (result) should be saved correctly

### Steps To Reproduce

set `store_failures` to true and use any test containing boolean value like this:
```
      - name: some_column_name
        quote: true
        tests:
          - accepted_values:
              values:
                - 0
                - 1
              quote: false
 ```       

### Operating System

linux

### dbt version

1.1.0/1.2.1

### Trino Server version

1.1.0/1.2.2

### Python version

3.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
Solved by https://github.com/starburstdata/dbt-trino/pull/141
