### ISSUE TITLE
discussion: dbt-core's feedback from initial review for adapter verification

### ISSUE THREAD

**Issue by dataders** [starburstdata/dbt-trino#142]
_** would have been a Discussion if they were enabled for this repo **_

as part of our new adapter verification process, the dbt core adapters engineering team and I met today to do a high-level review of the dbt-trino codebase. good news, your adapter passes the sniff test! That means that while the engineers haven’t yet had the time to review every single line of code (though they plan to in the next few sprints), there are no glaring red flags that prevent the adapter from being verified.

That said, here's some notes of things we noticed:
- it's great to see that Trino works without having to override hardly any `SQLAdapter` methods.
- It took a moment to realize why `TrinoCredentialsFactory` needed to exist. But using dataclass parameter validation to guide users to the correct sets of profile fields is a great choice. Perhaps though there's a way we can work to make this easier.
https://github.com/starburstdata/dbt-trino/blob/e9194b197228d7feb60f7eb204d0171efe5273b4/dbt/adapters/trino/connections.py#L30-L45
- is there anything unique about Trino today w.r.t. prepared statements & bindings? or is that legacy code?
https://github.com/starburstdata/dbt-trino/blob/e9194b197228d7feb60f7eb204d0171efe5273b4/dbt/adapters/trino/connections.py#L333-L353
- can you give more context on why you needed to parse the DatabaseError message? 
https://github.com/starburstdata/dbt-trino/blob/e9194b197228d7feb60f7eb204d0171efe5273b4/dbt/adapters/trino/connections.py#L360-L368

For example:
- do you think that some of the logic in `TrinoAdapter.add_query()` could upstream into dbt-core?
https://github.com/starburstdata/dbt-trino/blob/e9194b197228d7feb60f7eb204d0171efe5273b4/dbt/adapters/trino/connections.py#L416-L450

please let us know if there any other particular areas you’d like us to review more closely. Looking forward to collaborating!

**Comment by mdesmet** [comment]
> It took a moment to realize why TrinoCredentialsFactory needed to exist. But using dataclass parameter validation to guide users to the correct sets of profile fields is a great choice. Perhaps though there's a way we can work to make this easier.

Agreed, I already wanted to discuss that with you. The result is actually nice but the implementation not so.

> is there anything unique about Trino today w.r.t. prepared statements & bindings? or is that legacy code?

This code is indeed scheduled to be removed. By default we use prepared statements, using this code is behind a connection parameter.

> can you give more context on why you needed to parse the DatabaseError message?

Not completely sure about this one. I think it might be that we didn't always throw dbapi exceptions before (fixed for some time already in trino-python-client). We should look into this one.

**Comment by dataders** [comment]
this review cycle is finished. this adapter is verified as soon as the joint support agreement is signed!
