### ISSUE TITLE
Analyze whether the migration of dbt_utils `current_timestamp` macros in dbt 1.3.0 affects dbt-trino

### ISSUE THREAD

**Issue by findinpath** [starburstdata/dbt-trino#156]
### Describe the feature

https://github.com/dbt-labs/dbt-core/releases/tag/v1.3.0

Migrate dbt-utils current_timestamp macros into core + adapters (https://github.com/dbt-labs/dbt-core/issues/5521, https://github.com/dbt-labs/dbt-core/pull/5838)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
See following note in the dbt core PR.

As we consistently used current_timestamp we are not affected by this issue.

```
/* {#
    DEPRECATED: DO NOT USE IN NEW PROJECTS
    This is ONLY to handle the fact that Snowflake + Postgres had functionally
    different implementations of {{ dbt.current_timestamp }} + {{ dbt_utils.current_timestamp }}
    If you had a project or package that called {{ dbt_utils.current_timestamp() }}, you should
    continue to use this macro to guarantee identical behavior on those two databases.
#} */
```
