### ISSUE TITLE
Potential issue with the incremental materialization failing when used with a custom schema

### ISSUE THREAD

**Issue by rahulj51** [starburstdata/dbt-trino#17]
I tried using the materialization with `presto` (not `trino`) and found that it works perfectly except if a custom schema is used.

This line
https://github.com/starburstdata/dbt-trino/blob/80884475eb921f27a09effa2fbc10b93309599a8/dbt/include/trino/macros/materializations/incremental.sql#L6

strips-off the database and schema names from the temp relation causing the query to fail. 

I haven't yet had the chance to test this with `trino` but I suspect that the behaviour would be the same.

**Comment by Btwitzke** [comment]
This issue does exist in trino as well. I can confirm that using a custom schema with the incremental model does strip off the database/schema. This causes the model to fail on the insert statement.

**Comment by Btwitzke** [comment]
All that needs to be completed here is changing those variables for database and schema to true in the macro. I tested this by changing them in my env and incremental works. 

`select {{dest_cols_csv}} from {{ tmp_relation.include(database=true, schema=true) }}; `

**Comment by findinpath** [comment]
@Btwitzke  could you please provide a sample project to easily test the change you are suggesting?
