### ISSUE TITLE
Enable column-level comments in views tests 

### ISSUE THREAD

**Issue by hovaesco** [starburstdata/dbt-trino#172]
### Describe the feature

Starting from Trino 402 https://github.com/trinodb/trino/pull/13800 will support column-level comments in views. Once Trino 402 will be relased, enable tests in `test_persist_docs.py` and amend README to reflect this functionality. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by findinpath** [comment]
I'll address this one after the next Trino release in #173
