### ISSUE TITLE
Replacing view with table fails

### ISSUE THREAD

**Issue by wrb2** [starburstdata/dbt-trino#184]
### Expected behavior

Switching materialization from view to a table should work with no manual steps.

### Actual behavior

When I switch materialization from view to a table, instead of view being replace by table I get error

`TrinoUserError(type=USER_ERROR, name=GENERIC_USER_ERROR, message="line 1:1: Table '<REDACTED>' does not exist, but a view with that name exists. Did you mean DROP VIEW <REDACTED>?`

### Steps To Reproduce

1. Create a view model.
2. Switch view model to table.

### Operating System

MacOS

### dbt version

1.3.0

### Trino Server version

402-e.0

### Python version

3.10.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wrb2** [comment]
I tested it with `dbt-core==1.3.1 `and `dbt-trino==1.3.1` and it still happens.

What is interesting is that this works with Trino 393, but it fails on 402. Did handling view in metadata changed by any chance?

**Comment by bohyn** [comment]
This looks like a quite serious regression. Is there any note in the backward incompatible changes section in release notes regarding this?

**Comment by findinpath** [comment]
@przemekak can you please have a look into this? 

It may have to do with `on_table_exists` feature a8030e12

**Comment by wrb2** [comment]
I did some more digging and the views in question somehow appear in `information_schema` as tables (in both Trino versions). But I created new views and was not able to reproduce this - those show in information_schema as views. But creating more views in original schema makes them show up as tables?

So I think this is not dbt-trino issue but our Trinos getting into some bizarre state.

**Comment by findinpath** [comment]
Try out `system.flush_metadata_cache()`  from https://trino.io/docs/current/connector/hive.html#procedures and please do tell us whether this solved your problem.

**Comment by wrb2** [comment]
I have no idea what is going on.

     trino> create view catalog.schema.test_view as select 1 as x;
     trino> select * from catalog.information_schema.tables where table_schema = 'schema' and table_catalog = 'catalog';

     table_catalog |    table_schema     | table_name | table_type 
    ---------------+---------------------+------------+------------
     catalog       | schema              | test_view  | BASE TABLE 

     trino> create view catalog2.schema.test_view as select 1 as x;
     trino> select * from catalog2.information_schema.tables where table_schema = 'schema' and table_catalog = 'catalog2';

     table_catalog |    table_schema     | table_name | table_type 
    ---------------+---------------------+------------+------------
     catalog2      | schema              | test_view  | VIEW

The flush doesn't change anything.

**Comment by wrb2** [comment]
Anyway this is for sure not dbt-trino problem, since it's the Trino's metadata that is a mess. I'll close this issue, sorry for the confusion.

**Comment by findinpath** [comment]
@wrb2 if both of the catalogs share the same metastore, what you see it is normal.
I'd very much appreciate if you give this issue a bit more time and get to the bottom of the problem to eventually avoid having other users go through the same kind of issue as well.

**Comment by wrb2** [comment]
Could you elaborate on how it is normal? Why should I create a view and see it as a table?

**Comment by findinpath** [comment]
> @wrb2 if both of the catalogs share the same metastore, what you see it is normal.

On a second look, it it not normal.

Can you provide a simple trino based reproduction scenario so that we can address the isuse on Trino?

**Comment by findinpath** [comment]
I tested locally with starburst-enterprise `402-e.0`  , Hive connector and Glue and couldn't seem to reproduce the issue.

```
trino:glue> create view test_view as select 1 as x;
CREATE VIEW
trino:glue> select * from test_view;
 x 
---
 1 
(1 row)

 select * from hive.information_schema.tables ;
 table_catalog |    table_schema    |    table_name    | table_type 
---------------+--------------------+------------------+------------
 hive          | information_schema | columns          | BASE TABLE 
 hive          | information_schema | tables           | BASE TABLE 
 hive          | information_schema | views            | BASE TABLE 
 hive          | information_schema | schemata         | BASE TABLE 
 hive          | information_schema | table_privileges | BASE TABLE 
 hive          | information_schema | roles            | BASE TABLE 
 hive          | information_schema | applicable_roles | BASE TABLE 
 hive          | information_schema | enabled_roles    | BASE TABLE 
 hive          | glue               | test_view        | VIEW       
(9 rows)
```


My `hive.properties`:

```
connector.name=hive

hive.metastore=glue
hive.metastore.glue.region=eu-central-1
hive.metastore.glue.aws-access-key=${ENV:HIVE_S3_ACCESS_KEY}
hive.metastore.glue.aws-secret-key=${ENV:HIVE_S3_SECRET_KEY}
hive.s3.endpoint=https://s3.eu-central-1.amazonaws.com
hive.s3.aws-access-key=${ENV:HIVE_S3_ACCESS_KEY}
hive.s3.aws-secret-key=${ENV:HIVE_S3_SECRET_KEY}
hive.s3.path-style-access=false
hive.non-managed-table-writes-enabled=true

hive.allow-drop-table=true
hive.allow-rename-table=true
```

@wrb2  I need a few pointers on how to reproduce the behaviour 

```
trino> create view catalog.schema.test_view as select 1 as x;
 trino> select * from catalog.information_schema.tables where table_schema = 'schema' and table_catalog = 'catalog';

 table_catalog |    table_schema     | table_name | table_type 
---------------+---------------------+------------+------------
 catalog       | schema              | test_view  | BASE TABLE 
```

**Comment by mdesmet** [comment]
@findinpath :

See here the reproduction steps.

```
trino> create view hive.default.test as select 1 x;
CREATE VIEW
trino> select * from delta.information_schema.tables;
 table_catalog |    table_schema    |    table_name    | table_type 
---------------+--------------------+------------------+------------
 delta         | information_schema | columns          | BASE TABLE 
 delta         | information_schema | tables           | BASE TABLE 
 delta         | information_schema | views            | BASE TABLE 
 delta         | information_schema | schemata         | BASE TABLE 
 delta         | information_schema | table_privileges | BASE TABLE 
 delta         | information_schema | roles            | BASE TABLE 
 delta         | information_schema | applicable_roles | BASE TABLE 
 delta         | information_schema | enabled_roles    | BASE TABLE 
 delta         | default            | test             | BASE TABLE 
```

**Comment by findinpath** [comment]
I have created https://github.com/trinodb/trino/issues/15231 Trino issue to track this problem
