### ISSUE TITLE
Temp/backup relations do not use model alias for table materialization

### ISSUE THREAD

**Issue by rikturr** [starburstdata/dbt-trino#185]
### Expected behavior

We override the `generate_alias_name` macro in our project to generate different table names for dev vs prod. We would expect the temp table name to look like `alias_name__dbt_tmp`. 

### Actual behavior

The final identifier gets written out correctly, but we notice that the temp and backup tables do not use the alias, but instead look like `model_name__dbt_tmp`. 

I believe the issue is that lines 3-4 in the [table materialization macro](https://github.com/dbt-labs/dbt-presto/blob/0.20.latest/dbt/include/presto/macros/materializations/table.sql) use `model['name']` rather than `model['alias']`. I'd be happy to submit a change for this if that is all that is needed

### Steps To Reproduce

For example, with a model called "model1" configured like:

```
{{ config(alias="my_new_name", materialization=table) }}
```

The temp CTAS would look like:
```
create table "catalog"."schema"."model1__dbt_tmp"
...

```

where we would expect the identifier to be `my_new_name__dbt_tmp`. This does not happen for incremental materializations, only table.

### Operating System

MacOS

### dbt version

0.20.0 (technically we're on dbt-presto, but looking to upgrade to dbt-trino soon)

### Trino Server version

386

### Python version

3.8.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
Does the bug exist in the dbt-trino version (if yes, in which?) or in dbt-presto 0.20.0?

**Comment by rikturr** [comment]
> Does the bug exist in the dbt-trino version (if yes, in which?) or in dbt-presto 0.20.0?

I didn't test the Trino version, but I see that the macro in the latest dbt-trino still uses model names instead of aliases: https://github.com/starburstdata/dbt-trino/blob/master/dbt/include/trino/macros/materializations/table.sql#L9

**Comment by mdesmet** [comment]
IMHO the recommended and safer way to split environments would be to setup a dev and prod schema in your profiles.yaml instead of changing the alias. What do you think about that?

**Comment by rikturr** [comment]
> IMHO the recommended and safer way to split environments would be to setup a dev and prod schema in your profiles.yaml instead of changing the alias. What do you think about that?

I agree, and we do have separate profiles but due to the nature of our database permissions we need to take it further with this alias change. We require a shared dev schema, and the models are configured to belong in various different schemas for prod. So when working on dev, we have a macro to concatenate the prod schema name and table name into the alias to make sure there are no collisions when various users are performing development at the same time. With this bug, the temp table names are still colliding
