### ISSUE TITLE
Insert query ID in adapter response

### ISSUE THREAD

**Issue by louis-zhang-unity3d** [starburstdata/dbt-trino#186]
### Describe the feature

Currently the [adapter response of the Trino connector](https://github.com/starburstdata/dbt-trino/blob/527954c6408b9f526c6680906ba9b9f4521d7462/dbt/adapters/trino/connections.py#L431) is by default a "SUCCESS" message . By looking up in the table `system.runtime.queries`, the Trino `query_id` provides access to useful performance metadata that can be used for observability.  Including this attribute in the adapter response would greatly enhance observability of dbt models by enabling traceability for each model run. 

The `query_id` can be accessed by the `._query.query_id` attribute of the `trino.dbapi.Cursor` object. 

Other dbt providers (i.e. BigQuery, Snowflake) add a similar ID to their adapter response as well. 

### Who will benefit?

This will benefit all data teams looking to monitor the performance of their dbt model runs over time, e.g. runtime, successes/failures, etc. Each dbt model run can be tied back to underlying metadata within trino itself. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by findinpath** [comment]
@louis-zhang-unity3d could you please add more details regarding the _benefit_ part? Where could the query id be used/persisted for being further used? Do you mean something like a time series db label?

**Comment by louis-zhang-unity3d** [comment]
@findinpath The `system.runtime.queries` table (https://trino.io/docs/current/connector/system.html#runtime-queries)
contains information about currently and recently running queries on the Trino cluster. From this table, which contains the query_id as a column, you can find out the original query SQL text, the identity of the user who ran the query, and performance information about the query, including how long the query was queued and analyzed.  Our own use case would be to retrieve the `adapter_response` field from [DBT's run_results.json output](https://docs.getdbt.com/reference/artifacts/run-results-json) to get the query ID and retrieve the metadata from `system.runtime.queries`. 

Examples of the other adapters including this are 
* BigQuery https://github.com/dbt-labs/dbt-bigquery/blob/d4993cc848214f997c4a0cf1716656fc7a70bd02/dbt/adapters/bigquery/connections.py#L514 
* Snowflake https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L358

**Comment by mdesmet** [comment]
Hi @louis-zhang-unity3d, I think that change is very logical and welcome but we should probably also add a public field `cursor.query_id` in Trino Python Client's `Cursor` to accommodate for this.

**Comment by mdesmet** [comment]
I added a PR on trino-python-client to expose the `query_id`: https://github.com/trinodb/trino-python-client/pull/295

@louis-zhang-unity3d : If you want you can already start working on it, ping us if you need some help!

**Comment by aezomz** [comment]
Whats the status for this, @louis-zhang-unity3d  ? I am looking for the same as well.

**Comment by louis-zhang-unity3d** [comment]
@mdesmet could I get permissions to push to a remote branch and open a PR? thanks!

**Comment by hovaesco** [comment]
You would need to create a fork of `dbt-trino` repository first and then open a pull request from there.

**Comment by aezomz** [comment]
Do you all think it make sense to store the compiled query as well?
I use DBT test and will like to store the compiled query result for reference, especially tests that are failing.
