### ISSUE TITLE
Incremental materialization doesn't drop temp table

### ISSUE THREAD

**Issue by wrb2** [starburstdata/dbt-trino#195]
### Expected behavior

When something goes wrong during incremental materialization, rerunning dbt should fix the problem.

### Actual behavior

When something goes wrong during incremental materialization, the temp table isn't dropped so once something goes wrong, dbt can never recover and needs someone to manually drop the temp table for things to work again.

### Steps To Reproduce

1. Run incremental model that fails for operational reasons (e.g. Trino being unstable). 
2. Run it again.

Dbt-trino creates temporary relation to hold the data that it then appends. That gets cleaned up on success but not before run, so if things go wrong the relation stays there, until cleaned up manually.

### Log output/Screenshots

```
10:03:25  Database Error in model <redacted> (models/<redacted>.sql)
10:03:25    TrinoUserError(type=USER_ERROR, name=TABLE_ALREADY_EXISTS, message="line 1:1: Destination table '<redacted>' already exists", query_id=20221211_095653_13629_vchpy)

```

### Operating System

MacOS

### dbt version

1.3.0

### Trino Server version

393-e.1

### Python version

3.8.10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wrb2** [comment]
I think the fix would be basically add `{% do adapter.drop_relation(tmp_relation) %}` after https://github.com/starburstdata/dbt-trino/blob/0aa3af4852742e328a5f58073ee17c8a24fe5b0e/dbt/include/trino/macros/materializations/incremental.sql#L66
but now that I'm looking at it, it seems strange that it even does table - I wonder if `views_enabled` should be default?

**Comment by mdesmet** [comment]
You are right it should default to `true` according to the docs.
