### ISSUE TITLE
upgrade to support dbt-core v1.4.0

### ISSUE THREAD

**Issue by damian3031** [starburstdata/dbt-trino#213]
dbt-core v1.4.0 was just [released](https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.0). Upgrade `dbt-trino` adapter to support it.

[dbt docs on Upgrading to v1.4 (prerelease)](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.4)

**Comment by findinpath** [comment]
FYI https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.1 is out as well with a regression fix.
