### ISSUE TITLE
Fails with DBT 1.0.0

### ISSUE THREAD

**Issue by pixie79** [starburstdata/dbt-trino#22]
I think this needs an update to support the current version of DBT.

When running "dbt debug" the following error is returned:

dbt was unable to connect to the specified database.
The database returned the following error:

  >Runtime Error
  'str' object has no attribute '_message'

DBT it set to use the trino driver which in turn is configured to talk to an AWS Data Catalog and S3

**Comment by hovaesco** [comment]
Hi!

Thanks for raising the issue.

We are aware that dbt-core v1.0.0 is not yet supported with dbt-trino adapter. The plan is to upgrade the adapter in the following days. 

I am going to keep you posted on that.

**Comment by hovaesco** [comment]
https://github.com/starburstdata/dbt-trino/pull/25

**Comment by hovaesco** [comment]
`dbt-trino v1.0.0` released
