### ISSUE TITLE
Support release branches

### ISSUE THREAD

**Issue by mdesmet** [starburstdata/dbt-trino#231]
### Describe the feature

- CREATE BRANCH for each minor release based on the latest patch tag for each minor
- CREATE CHANGELOG on master branch that refers each minor version latest changeling on the relevant release branch
- Make every release compatible with version bump (standardised setup.py and __version__.py)
- Ensure master + release branches are tested on push
- Ensure master + release branches are tested on pull request

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by damian3031** [comment]
Currently [dbt trino release workflow](https://github.com/starburstdata/dbt-trino/blob/master/.github/workflows/release.yml#L54-L66) uses [this](https://github.com/actions/create-release) github action. Unfortunately, this github action sets every release as latest, so while making backport and releasing 1.0.4, it would be set as latest github release. There is [make_latest](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release--parameters) github API parameter which could be set to false, to avoid setting backported releases as latest ones. Unfortunately, this GH action doesn't support this parameter, and will never do, as this repository is archived.
So, it would require to manually change which version is latest after releasing backported version, or some refactor in a release workflow.

There is another gh action which I used in PyTrino release workflow, which has [pending PR](https://github.com/softprops/action-gh-release/pull/304) for addition of this parameter, maybe it could be used instead after adding this `make_latest` option there.

**Comment by mdesmet** [comment]
> Unfortunately, this GH action doesn't support this parameter, and will never do, as this repository is archived.
> 
> So, it would require to manually change which version is latest after releasing backported version, or some refactor in a release workflow.

As discussed offline, let's not worry about this.
