### ISSUE TITLE
`host` value parsing: more flexible and fault-tolerant 

### ISSUE THREAD

**Issue by dataders** [starburstdata/dbt-trino#245]
### Describe the feature

It was not immediately clear to me (especially based on the impending dbt Cloud UI) that you cannot include the `http://` prefix in the `host` field of a Starburst Galaxy URL. I see there is an `http_scheme` field, but perhaps that field isn't necessary and can just be inferred from the provided host?

I want to say I also had issues when the provided endpoint URL ended in with a `/`. Happy to add more example.

### Describe alternatives you've considered

Alternatively, how this field works could be better explained in documentation or in UI tooltips

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Fix provided in https://github.com/trinodb/trino-python-client/pull/340
