### ISSUE TITLE
Merge Strategy creating model__dbt_tmp at the same S3 location as configured in config where my main table got created

### ISSUE THREAD

**Issue by aman29jha** [starburstdata/dbt-trino#255]
### Expected behavior

{{
    config(
        materialized = 'incremental',
        incremental_strategy='merge',
        unique_key= 'epoch',
        properties={
          "partitioned_by": "ARRAY['epoch']",
          "location": "'s3a://bucket_name/table_name"}
    )
}}
 SELECT
from_unixtime([1619445982](tel:1619445982)) as epoch_to_local ,
1619445982000 as epoch

With delta as a catalog, we are trying to do this, however post the table creation, during the second execution the same got failed.

The reason of the failure is during the second execution the merge is creating the model__dbt_tmp table in the same location where the main table is which should not be the case.

### Actual behavior

The query shouldn't fail and the temp should use some directory other than the temp one.

### Steps To Reproduce

{{
    config(
        materialized = 'incremental',
        incremental_strategy='merge',
        unique_key= 'epoch',
        properties={
          "partitioned_by": "ARRAY['epoch']",
          "location": "'s3a://bucket_name/table_name"}
    )
}}
 SELECT
from_unixtime([1619445982](tel:1619445982)) as epoch_to_local ,
1619445982000 as epoch

Use the following configuration and try to run the query twice 

### Operating System

mac 

### dbt version

1.4.1

### Trino Server version

398

### Python version

Python 3.9.13

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
As mentioned on Slack using `location` as a table property is not supported as this creates an external table, ie data is not dropped on delete.

Please add the dbt.log for the initial run and the incremental run to confirm.

**Comment by damian3031** [comment]
@aman29jha please provide logs, otherwise we will close the issue
