### ISSUE TITLE
compatibility pin the trino python client

### ISSUE THREAD

**Issue by dataders** [starburstdata/dbt-trino#261]
### Describe the feature

As it stands, everytime [trino-python-client](https://github.com/trinodb/trino-python-client) has a new update, it requires that dbt-trino cuts a new patch release. #257 is an example of this.

This new patch release will additionally have to be backported to any currently "supported in Cloud" minor release. This does not sound fun.

The solution within this repo is to "compatibility pin" the dependency on the python client, `trino` instead of an exact pin. As in `"trino~=0.321.0"` or `"trino~=0.321"` instead of the below.
https://github.com/starburstdata/dbt-trino/blob/7f72784ca9f135edb58e6ae74241864ccc5cbcf8/setup.py#L89

However this solution isn't perfect as it would auto-include new versions of the python client, which, imo, is a hard pill to swallow given that the client doesn't follow [semantic versioning](semver.org) for releases.

I already opened [trino-python-client#345](https://github.com/trinodb/trino-python-client/discussions/345) and I strongly suggest that the client library adopt Semantic Versioning by:
1. releasing a 1.0 version of the software and
2. bucketizing releases into major, minor, and patch versions

### Who will benefit?

all users of this client, but especially the maintainers and users of dbt-trino

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
For now we'll unpin the trino-python-client. trino-python-client doesn't follow the semantic versioning but there is obviously the commitment that the protocol is stable.
