### ISSUE TITLE
Add cleanup for tests on galaxy

### ISSUE THREAD

**Issue by damian3031** [starburstdata/dbt-trino#267]
Some schemas aren't cleaned up after running tests on galaxy. It seems to be related to [test_store_failures](https://github.com/starburstdata/dbt-trino/blob/master/tests/functional/adapter/store_failures/test_store_failures.py) and [test_custom_schema](https://github.com/starburstdata/dbt-trino/blob/master/tests/functional/adapter/test_custom_schema.py) tests.

Add appropriate cleanup of these schemas.
<img width="609" alt="Screenshot 2023-03-09 at 12 45 34" src="https://user-images.githubusercontent.com/113946744/224014325-191b714c-dd83-45c0-b8c8-222b23ad1655.png">

**Comment by damian3031** [comment]
The reason for this issue is that dbt test suite is only cleaning up default schema while running test suite. There is already a GitHub issue in `dbt-core` repo for this: https://github.com/dbt-labs/dbt-core/issues/7030

For now, we could add some custom cleanup on our side, or maybe just manually clean up these residues on Galaxy, say, once a month, until root cause is fixed on `dbt-core` side.

**Comment by hovaesco** [comment]
It's addressed.
