### ISSUE TITLE
Alter table not working for managed tables

### ISSUE THREAD

**Issue by sandip-yadav** [starburstdata/dbt-trino#269]
### Expected behavior

Renaming tables should be working with managed tables. Currently I am trying to create a model random_1 using table materialisation and creating the tables in a managed location in s3 so dbt is creating a random_1__dbt_tmp and trying to rename it to random_1 and should work as expected.

### Actual behavior

I am trying to create model with table materialisation and dbt is first creating a temp table with random_1__dbt_tmp and then rename it to the actual model name (random_1) and this is where it's failing with error as renaming not allowed in external tables. My trino is running on delta lake connector and I have defined the s3 location in schema itself. With external table its working as expected. Attaching the logs for reference. My trino version is 409 and dbt-trino version is 1.4.4.

### Steps To Reproduce

create a managed table in dbt with table materialisation. 
setup - trino with delta lake connector
storage - s3

### Log output/Screenshots

``
============================== 2023-03-10 05:46:04.831550 | 62d9ddb8-82b1-46fa-bef3-2d766ef64886 ==============================
05:46:04.831550 [info ] [MainThread]: Running with dbt=1.4.4
05:46:04.834818 [debug] [MainThread]: running dbt with arguments {'debug': True, 'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/nj/.dbt', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'select': ['random_1'], 'which': 'run', 'rpc_method': 'run', 'indirect_selection': 'eager'}
05:46:04.835369 [debug] [MainThread]: Tracking: tracking
05:46:05.069816 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6bd4e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6ba5190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6ba5760>]}
05:46:05.085841 [debug] [MainThread]: checksum: 170d819e8a7f11e09c497566dd7f61e1355cb9fb514921503937b951cb4a2250, vars: {}, profile: None, target: None, version: 1.4.4
05:46:05.198462 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
05:46:05.198985 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
05:46:05.200462 [warn ] [MainThread]: [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- seeds.dwh_pp_trino_common
05:46:05.208878 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '62d9ddb8-82b1-46fa-bef3-2d766ef64886', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6f360d0>]}
05:46:05.224631 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '62d9ddb8-82b1-46fa-bef3-2d766ef64886', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6ca7c70>]}
05:46:05.225934 [info ] [MainThread]: Found 18 models, 0 tests, 0 snapshots, 0 analyses, 313 macros, 0 operations, 0 seed files, 49 sources, 0 exposures, 0 metrics
05:46:05.226449 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '62d9ddb8-82b1-46fa-bef3-2d766ef64886', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6ca7ca0>]}
05:46:05.229406 [info ] [MainThread]: 
05:46:05.231792 [debug] [MainThread]: Acquiring new trino connection 'master'
05:46:05.233303 [debug] [ThreadPool]: Acquiring new trino connection 'list_delta'
05:46:05.249229 [debug] [ThreadPool]: Using trino connection "list_delta"
05:46:05.249845 [debug] [ThreadPool]: On list_delta: select distinct schema_name
    from delta.INFORMATION_SCHEMA.schemata
05:46:05.250400 [debug] [ThreadPool]: Opening a new connection, currently in state init
05:46:06.442830 [debug] [ThreadPool]: SQL status: SUCCESS in 1 seconds
05:46:06.447027 [debug] [ThreadPool]: On list_delta: Close
05:46:06.452128 [debug] [ThreadPool]: Acquiring new trino connection 'list_delta_loadtest'
05:46:06.464109 [debug] [ThreadPool]: Using trino connection "list_delta_loadtest"
05:46:06.464713 [debug] [ThreadPool]: On list_delta_loadtest: select
      table_catalog as database,
      table_name as name,
      table_schema as schema,
      case when table_type = 'BASE TABLE' then 'table'
           when table_type = 'VIEW' then 'view'
           else table_type
      end as table_type
    from delta.INFORMATION_SCHEMA.tables
    where table_schema = 'loadtest'
05:46:06.465163 [debug] [ThreadPool]: Opening a new connection, currently in state closed
05:46:06.871527 [debug] [ThreadPool]: SQL status: SUCCESS in 0 seconds
05:46:06.874823 [debug] [ThreadPool]: On list_delta_loadtest: ROLLBACK
05:46:06.875671 [debug] [ThreadPool]: On list_delta_loadtest: Close
05:46:06.881946 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '62d9ddb8-82b1-46fa-bef3-2d766ef64886', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6ca76a0>]}
05:46:06.882960 [debug] [MainThread]: On master: COMMIT
05:46:06.884013 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
05:46:06.884517 [info ] [MainThread]: 
05:46:06.894029 [debug] [Thread-1  ]: Began running node model.dwh_pp_trino_common.random_1
05:46:06.894802 [info ] [Thread-1  ]: 1 of 1 START sql table model loadtest.random_1 ................................. [RUN]
05:46:06.895967 [debug] [Thread-1  ]: Acquiring new trino connection 'model.dwh_pp_trino_common.random_1'
05:46:06.896493 [debug] [Thread-1  ]: Began compiling node model.dwh_pp_trino_common.random_1
05:46:06.901404 [debug] [Thread-1  ]: Writing injected SQL for node "model.dwh_pp_trino_common.random_1"
05:46:06.903128 [debug] [Thread-1  ]: Timing info for model.dwh_pp_trino_common.random_1 (compile): 2023-03-10 05:46:06.896904 => 2023-03-10 05:46:06.902976
05:46:06.903745 [debug] [Thread-1  ]: Began executing node model.dwh_pp_trino_common.random_1
05:46:06.946050 [debug] [Thread-1  ]: Writing runtime sql for node "model.dwh_pp_trino_common.random_1"
05:46:06.950861 [debug] [Thread-1  ]: Using trino connection "model.dwh_pp_trino_common.random_1"
05:46:06.951521 [debug] [Thread-1  ]: On model.dwh_pp_trino_common.random_1: create table delta.loadtest.random_1__dbt_tmp
    WITH (partitioned_by = ARRAY['p_date'])
  as (
    
with posting as (
select id,
       transactionid,
       postingid,
       createdat,
       p_date,
       amount,
       remarks,
       dense_rank() over (partition by id order by createdat desc) as rnk
from delta.loadtest.test_table_1 lp
)
select lm.id,
       lm.createdat,
       p.createdat as last_txn_date,
       p.amount as last_txn_amount,
       p.p_date,
       p.remarks,
       lm.ifi,
       json_query(lm.attrjson, 'lax$."account.pd-id"' omit quotes) product_id,
       lm.ifi_product_type
from delta.loadtest.test_table_2 lm
join 
posting p on lm.id = p.id
and p.rnk = 1
  )
05:46:06.952345 [debug] [Thread-1  ]: Opening a new connection, currently in state closed
05:54:33.884933 [debug] [Thread-1  ]: SQL status: SUCCESS in 507 seconds
05:54:33.898524 [debug] [Thread-1  ]: Using trino connection "model.dwh_pp_trino_common.random_1"
05:54:33.899204 [debug] [Thread-1  ]: On model.dwh_pp_trino_common.random_1: alter table delta.loadtest.random_1__dbt_tmp rename to delta.loadtest.random_1
05:54:34.579612 [debug] [Thread-1  ]: Trino adapter: Trino query id: 20230310_055434_00024_dghv7
05:54:34.580330 [debug] [Thread-1  ]: Trino adapter: Trino error: TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Renaming managed tables is not allowed with current metastore configuration", query_id=20230310_055434_00024_dghv7)
05:54:34.581088 [debug] [Thread-1  ]: Timing info for model.dwh_pp_trino_common.random_1 (execute): 2023-03-10 05:46:06.904151 => 2023-03-10 05:54:34.580980
05:54:34.581580 [debug] [Thread-1  ]: On model.dwh_pp_trino_common.random_1: ROLLBACK
05:54:34.581910 [debug] [Thread-1  ]: On model.dwh_pp_trino_common.random_1: Close
05:54:34.607367 [debug] [Thread-1  ]: Database Error in model random_1 (models/load_test/random_1.sql)
  TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Renaming managed tables is not allowed with current metastore configuration", query_id=20230310_055434_00024_dghv7)
  compiled Code at target/run/dwh_pp_trino_common/models/load_test/random_1.sql
05:54:34.608205 [debug] [Thread-1  ]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '62d9ddb8-82b1-46fa-bef3-2d766ef64886', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6f42d60>]}
05:54:34.609930 [error] [Thread-1  ]: 1 of 1 ERROR creating sql table model loadtest.random_1 ........................ [ERROR in 507.71s]
05:54:34.612237 [debug] [Thread-1  ]: Finished running node model.dwh_pp_trino_common.random_1
05:54:34.615639 [debug] [MainThread]: Acquiring new trino connection 'master'
05:54:34.616220 [debug] [MainThread]: On master: COMMIT
05:54:34.616943 [debug] [MainThread]: Connection 'master' was properly closed.
05:54:34.617304 [debug] [MainThread]: Connection 'model.dwh_pp_trino_common.random_1' was properly closed.
05:54:34.617676 [info ] [MainThread]: 
05:54:34.618035 [info ] [MainThread]: Finished running 1 table model in 0 hours 8 minutes and 29.39 seconds (509.39s).
05:54:34.618465 [debug] [MainThread]: Command end result
05:54:34.628170 [info ] [MainThread]: 
05:54:34.628805 [info ] [MainThread]: Completed with 1 error and 0 warnings:
05:54:34.629682 [info ] [MainThread]: 
05:54:34.630455 [error] [MainThread]: Database Error in model random_1 (models/load_test/random_1.sql)
05:54:34.631168 [error] [MainThread]:   TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Renaming managed tables is not allowed with current metastore configuration", query_id=20230310_055434_00024_dghv7)
05:54:34.631609 [error] [MainThread]:   compiled Code at target/run/dwh_pp_trino_common/models/load_test/random_1.sql
05:54:34.632129 [info ] [MainThread]: 
05:54:34.632625 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
05:54:34.633069 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6f8c9a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6f16a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fede6f465b0>]}
05:54:34.633530 [debug] [MainThread]: Flushing usage events
``

### Operating System

NA

### dbt version

1.4.4

### Trino Server version

409

### Python version

3.10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Aka-shi** [comment]
@mdesmet This used to work for us before we upgraded from 1.1.x to 1.2.4. Any ideas on how to resolve it? We don't use Glue metastore.

**Comment by sandip-yadav** [comment]
@mdesmet It's not feasible for us to switch to Glue metastore. Is there any other workaround to handle this.
