### ISSUE TITLE
support JWT authentication

### ISSUE THREAD

**Issue by dataders** [starburstdata/dbt-trino#31]
looks like [trino's python client supports JWT](https://github.com/trinodb/trino-python-client#jwt-authentication). An easy lift would be that a user could pass a JWT token as a target field in the user's `profiles.yml`.

The user below could then use some script to store the token as an environment variable.

Happy to advise on how this might work, LMK!

[relevant dbt Slack thread](https://getdbt.slack.com/archives/CNNPBQ24R/p1641840353003500)

>  I'm trying to connect dbt to presto as that is one of our data stores. The only way that we are able to connect to this is through okta verification using a token that lasts only 24 hours. From the looks of the documentation on the profile setup it looks like only ldap and kerberos is supported. Is there currently a way to fetch a token or is this something that would need to be done on my end to pass over to the presto profile?

**Comment by hovaesco** [comment]
Thanks, the proposed solution looks good, we can have an extra authentication kind and allow user to pass JWT token in `profiles.yml`

**Comment by hovaesco** [comment]
Closed by: https://github.com/starburstdata/dbt-trino/pull/32
