### ISSUE TITLE
Bug - dbt found models with the same name

### ISSUE THREAD

**Issue by vietsqsp** [starburstdata/dbt-trino#311]
### Expected behavior

I run:
```
dbt run --models +MY_MODEL+
```
in my trino project. I should get:
```
Running with dbt==1.5.0
...
```

### Actual behavior

I run:
```
dbt run --models +MY_MODEL+
```
in my trino project. I should get:
```
Compilation Error
  dbt found two models with the name "MY_MODEL".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when looking for ref("MY_MODEL").
  
  To fix this, change the name of one of these resources:
  - model.MY_TRINO_PROJECT.MY_MODEL (models/marts/MY_DATASET/target/compiled/MY_TRINO_PROJECT/models/marts/MY_DATASET/MY_MODEL.sql)
  - model.MY_TRINO_PROJECT.MY_MODEL (models/marts/MY_DATASET/MY_MODEL.sql)
```

### Steps To Reproduce

Run a model inside the dataset folder, not the project folder.

⚠️ This doesn't happen in my BigQuery project using a similar `dbt_project.yml` file.

```
❯ pip show dbt-trino
Name: dbt-trino
Version: 1.5.0
❯ pip show dbt-bigquery
Name: dbt-bigquery
Version: 1.5.1
```

### Operating System

macOS Ventura 13.4

### dbt version

1.5.0

### Trino Server version

1.5.0

### Python version

3.7.13

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by vietsqsp** [comment]
This is related to: https://github.com/dbt-labs/dbt-core/issues/7465

**Comment by hovaesco** [comment]
Hopefully `dbt-core v1.5.2` would solve the issue.

**Comment by hovaesco** [comment]
@vietsqsp have you tested it `v1.5.2` ?

**Comment by vietsqsp** [comment]
@hovaesco I actually upgraded to `dbt-core v1.5.3` and I don't have this error anymore. I'll close this ticket. Thank you.
