### ISSUE TITLE
Set the `comment` on `CREATE TABLE`

### ISSUE THREAD

**Issue by Fokko** [starburstdata/dbt-trino#318]
### Describe the feature

When you do a schema change on an Iceberg table, it will create a new version of the schema. This is not an issue, but would be best to avoid doing this as much as possible. Therefore when we set the `comment` directly when creating the table, Iceberg will not create a new version of the schema (because the comment is there already).

### Who will benefit?

Everyone using Iceberg.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by alaturqua** [comment]
Is it now always adding the comment?

Can this functionality be optional or be set to False on dbt_project.yml? 

It would be nice to be able to deactivate this functionality.

**Comment by Fokko** [comment]
Hey @alaturqua thanks for jumping in there.

You're right, the comment does not take the flag into account:

```
{{ config(
    persist_docs={"relation": true}
) }}
```

I agree that we should add this check here as well, let me see if that's possible.
