### ISSUE TITLE
Support elementary in improving data-quality capabilities

### ISSUE THREAD

**Issue by Firstero** [starburstdata/dbt-trino#351]
### Describe the feature

https://github.com/elementary-data/elementary/issues/739
Just as described in this issue, does dbt-rino have any plans to support elementary in improving data-quality capabilities using dbt-trino?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Firstero** [comment]
@leniartek Well, For me, all of my DBT projects are ETL tasks that run daily. I want to know the data quality of each model update, and Elementary provides a good monitoring framework for data anomaly detection, DBT testing, and execution statistics of DBT runs. This allows me to better understand any issues in my dbt etl processing and resolve them in a timely manner.

**Comment by hovaesco** [comment]
Support was added here https://github.com/elementary-data/elementary/pull/1378
