### ISSUE TITLE
Add Trino specific methods for casting types

### ISSUE THREAD

**Issue by findinpath** [starburstdata/dbt-trino#36]
As referenced in https://github.com/starburstdata/dbt-trino/issues/35

In https://github.com/dbt-labs/dbt-utils/blob/73a65562bf3d9b31a1eca0b27118056ad048d8fc/macros/cross_db_utils/datatypes.sql#L3-L6 there is a utility method used when casting to `string`

Add Trino specific `_type_xxx` methods in the Trino adapter and add also a corresponding unit test which creates a model by using `CAST` for all these types. Maybe this testing thought is wrong - if so, please use https://github.com/dbt-labs/dbt-utils#union_relations-source to test this functionality.

**Comment by harlequin** [comment]
Shall every Trino specific implementation stored in this repository even if this is from `dbt_utils` or `dbt_date`?

**Comment by mdesmet** [comment]
@harlequin : have you tried out dbt-trino-utils? It is now also available on [dbt hub](https://hub.getdbt.com/starburstdata/trino_utils/latest/). Let us know if it works for you!

**Comment by harlequin** [comment]
@mdesmet : I have included the dbt hub version in our project, I will execute some tests and will give you feedback.
From the current testing it seems to work well
