### ISSUE TITLE
Support `CREATE OR REPLACE`

### ISSUE THREAD

**Issue by Fokko** [starburstdata/dbt-trino#371]
### Describe the feature

Hey everyone!

I'm delighted to see `CREATE OR REPLACE` support in Trino: https://github.com/trinodb/trino/issues/13180

This will both:

- History of the table will be preserved in the Iceberg metadata, making it more transparent to the user what happened to the table.
- Make the execution of the pipeline faster, since fewer statements are being issued

### Describe alternatives you've considered

I would love to work on this, but my main question is how to determine if this is supported. I checked, but didn't find any minimal version to enable certain features.

### Who will benefit?

Everyone using Iceberg in Trino 🚀 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
I'm not aware of anyone working on this, let's introduce it as a separate strategy configured as `on_table_exists = 'replace'`.

I don't think we have a way to determine if this is supported on server side, please correct me if I'm wrong @mdesmet

**Comment by mosabua** [comment]
Theoretically you could get the version of the server (via various means including version() function) and decide with that info. The problem is that it will be different for each connector ...
