### ISSUE TITLE
Support `Password file` authentication type?

### ISSUE THREAD

**Issue by narrowizard** [starburstdata/dbt-trino#38]
I can only find `ldap` method to autentication trino server(With user and password), does it support [password file](https://trino.io/docs/current/security/password-file.html) configed trino server? If not, can you add this support?  
I've tried but got error as following
```
$ dbt run
05:33:21  Running with dbt=1.0.1
05:33:21  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 167 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
05:33:21  
05:33:23  Encountered an error:
Runtime Error
  Runtime Error
    error 401: b'Unauthorized'
```

**Comment by hovaesco** [comment]
Hi,
Password file authentication is supported by `ldap` method. Are you able to login to Trino via Web UI or via CLI using your credentials?

**Comment by narrowizard** [comment]
Thank u for your reply. After some trying, I have connected successfully to my trino server which is `password file` configed. I think it will be better to add some comment to method `ldap` to tell other password based method is also supported, if possible.  
Closed this issue.
