### ISSUE TITLE
deltalake rename managed table not allowed arised

### ISSUE THREAD

**Issue by ZergRocks** [starburstdata/dbt-trino#382]
### Expected behavior

dbt run with database delta option should be completed successfully after docker compose up

### Actual behavior

- `docker compose up`
- `dbt init {trino example}`
- set dbt profile as 
  ```
  trino:
    target: dev
    outputs:
      dev:
        type: trino
        method: none
        user: commander
        host: localhost
        port: 8080
        database: delta
        schema: dbt
  ```
- `dbt run` # should be run successfully

### Steps To Reproduce

wrote on `Actual behavior`

### Log output/Screenshots

```
11:18:57  Running with dbt=1.7.4
11:18:58  Registered adapter: trino=1.7.1
11:18:58  Found 2 models, 4 tests, 0 sources, 0 exposures, 0 metrics, 421 macros, 0 groups, 0 semantic models
11:18:58
11:19:02  Concurrency: 1 threads (target='dev')
11:19:02
11:19:02  1 of 2 START sql table model dbt.my_first_dbt_model ............................ [RUN]

11:19:11  1 of 2 ERROR creating sql table model dbt.my_first_dbt_model ................... [ERROR in 9.31s]
11:19:11  2 of 2 SKIP relation dbt.my_second_dbt_model ................................... [SKIP]
11:19:11
11:19:11  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 13.53 seconds (13.53s).
11:19:11
11:19:11  Completed with 1 error and 0 warnings:
11:19:11
11:19:11    Database Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
  TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Renaming managed tables is not allowed with current metastore configuration", query_id=20240114_111911_00004_s779w)
  compiled Code at target/run/trino/models/example/my_first_dbt_model.sql
11:19:11
11:19:11  Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2
```

### Operating System

ProductName:            macOS / ProductVersion:         13.1 / BuildVersion:           22C65

### dbt version

1.7.4

### Trino Server version

435

### Python version

3.11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
This [PR](https://github.com/trinodb/trino/pull/19991) will be a solution for your issue, then you can use `replace` strategy in your models starting from [dbt-trino v1.7.1](https://github.com/starburstdata/dbt-trino/blob/master/CHANGELOG.md#features).
