### ISSUE TITLE
Running codegen to generate source yaml fails

### ISSUE THREAD

**Issue by sl2902** [starburstdata/dbt-trino#411]
### Expected behavior

I would have expected the following command to generate yaml for the model files
dbt run-operation generate_source --args 'schema_name: my_schema'

Note - it works when I pass additional parameters such as the table names

### Actual behavior

```
19:42:41  Running with dbt=1.8.1
19:42:42  Registered adapter: trino=1.8.0
19:42:43  Found 11 models, 1 snapshot, 48 data tests, 1 seed, 6 sources, 893 macros, 1 unit test
19:42:44  Encountered an error while running operation: Database Error
  TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 18:28: mismatched input 'ilike'. Expecting: '%', '*', '+', '-', '.', '/', 'AND', 'AT', 'EXCEPT', 'FETCH', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', 'WINDOW', '[', '||', <EOF>, <predicate>", query_id=20240525_194243_10461_izpe7)
```

### Steps To Reproduce

Under models, I have a few folders which have their own folders

dbt run-operation generate_source --args 'schema_name: my_schema'

### Operating System

MacOS Sonoma 14.5

### dbt version

1.8.1

### Trino Server version

446-galaxy-1-u3-ge03ca8e8c2a

### Python version

3.8.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by damian3031** [comment]
`codegen.generate_source` utilizes [dbt_utils.get_tables_by_pattern_sql](https://github.com/dbt-labs/dbt-utils/blob/1.1.1/macros/sql/get_tables_by_pattern_sql.sql) underneath, where the `ilike` operator is used. Trino doesn't support [ilike](https://github.com/trinodb/trino/issues/2491) operator.

You need to install aditional package - [trino_utils](https://hub.getdbt.com/starburstdata/trino_utils/latest/), which provides a Trino-compatible implementation of this [macro](https://github.com/starburstdata/dbt-trino-utils/blob/0.6.0/macros/dbt_utils/sql/get_tables_by_pattern_sql.sql).

Please install trino_utils package according to [Installation Instructions](https://hub.getdbt.com/starburstdata/trino_utils/latest/#usage), and it should work.
