### ISSUE TITLE
When running "dbt test --store-fallures" trino reports "destination table XXX already exists"

### ISSUE THREAD

**Issue by thjwhite** [starburstdata/dbt-trino#420]
### Expected behavior

Store failures should result in same behavior as when creating normal models. It should do a drop and replace or rename.

### Actual behavior

Error destination table XXX already exists

### Steps To Reproduce

dbt test --store-fallures

dbt-trino using Glue catalog configuration. 

### Log output/Screenshots

  TrinoUserError(type=USER_ERROR, name=TABLE_ALREADY_EXISTS, message="line 7:5: Destination table 'glue."xxx_dbt_test__audit".xxxf' already exists", query_id=xxx)

### Operating System

osx

### dbt version

1.8.3

### Trino Server version

439

### Python version

3.12.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aalbu** [comment]
Verify how other adapters are handling multiple invocations of `dbt test --store-failures` and implement accordingly.

**Comment by hovaesco** [comment]
This is supported functionality and there are tests which creates the table, drops it and then recreates it https://github.com/starburstdata/dbt-trino/blob/master/tests/functional/adapter/store_failures/test_store_failures.py#L70

@thjwhite please share more info, config and logs to reproduce this scenario.

**Comment by hovaesco** [comment]
Not reproducible, closing.
