### ISSUE TITLE
Support for persist_docs in Starburst Galaxy

### ISSUE THREAD

**Issue by sdebruyn** [starburstdata/dbt-trino#421]
### Describe the feature

dbt supports a configuration option `persist_docs` which would store the dbt documentation in its target. It would be nice if this would enable us to store the documentation in Starburst Galaxy's data catalog.

[dbt documentation](https://docs.getdbt.com/reference/resource-configs/persist_docs)

### Who will benefit?

Every user of Starburst Galaxy

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
Hey @sdebruyn could you please explain what do you mean by store the documentation in Starburst Galaxy's data catalog?
Persist docs are supported for Starburst Galaxy.

**Comment by sdebruyn** [comment]
/
