### ISSUE TITLE
__dbt_tmp suffix in table location

### ISSUE THREAD

**Issue by damian3031** [starburstdata/dbt-trino#423]
With `on_table_exists = 'rename'` config, for object storage connectors, we create table under location which ends with suffix `__dbt_tmp`. This does not occur with `on_table_exists = 'replace'` config.

It is probably because of logic of creating `__dbt_tmp` suffixed table first and then renaming it to remove this suffix.

But this logic should be applied only when recreating an existing table, and not when creating a new table.

**Comment by nikita-sheremet-java-developer** [comment]
Same proble with `delete+insert` incremental strategy. First run works, second fails because it creates tmnp table with same location as original table.

**Comment by hovaesco** [comment]
@nikita-sheremet-java-developer it should fix your issue with `delete+insert` please test the fix and let us know whether it works.
