### ISSUE TITLE
dbt-core version pinning

### ISSUE THREAD

**Issue by smith-m** [starburstdata/dbt-trino#55]
Can dbt-trino be unpinned from the specific dbt-core patch version?

Per dbt's docs, this seems in line with the way they are managing dbt-core versioning:
https://docs.getdbt.com/docs/core-versions#upgrading-to-new-patch-versions

In my particular use case I want to take advantage of dbt-core's 1.0.4 patch.

**Comment by hovaesco** [comment]
Resolved by https://github.com/starburstdata/dbt-trino/commit/6822010551b647d92e514ea60d21b3023af888ed
