### ISSUE TITLE
Migrate to new framework for adapter testing during v1.1 upgrade

### ISSUE THREAD

**Issue by jtcohen6** [starburstdata/dbt-trino#57]
Hey `dbt-trino` maintainers! 

We've been developing a new framework for all integration/functional testing in `dbt-core`. One of our goals in the initiative has been to replace the suite of basic test cases for adapter plugins.

For now, the framework is comprised of:
- Pytest utilities included in `dbt-core==1.1.0b1`
- A set of "basic" test cases, at exact parity with the test cases built into the old `.dbtspec` / `pytest-dbt-adapter`

I have some draft docs (https://github.com/dbt-labs/docs.getdbt.com/pull/1263) for using the new framework: https://deploy-preview-1263--docs-getdbt-com.netlify.app/docs/contributing/testing-a-new-adapter

It should be much easier to:
- Override/reimplement test cases (as you've done [here](https://github.com/starburstdata/dbt-trino/blob/3e0bcc5665e846eccd5eaac63f8a660bb09a8998/test/integration/trino.dbtspec#L9-L19))
- "Opt into" test cases for more-advanced functionality, which we'll be gradually adding into the same package of adapter-facing test cases
- Add your own functional test cases for Trino-specific behavior, using the same built-in utilities, and reusing project fixtures if appropriate

If it proves helpful, you can also check out the way we've implemented the framework in some of our own adapter plugins:
- https://github.com/dbt-labs/dbt-redshift/pull/81
- https://github.com/dbt-labs/dbt-snowflake/pull/106
- https://github.com/dbt-labs/dbt-bigquery/pull/142 
- https://github.com/dbt-labs/dbt-spark/pull/299

Thanks for all the great work :)

**Comment by hovaesco** [comment]
Resolved by https://github.com/starburstdata/dbt-trino/pull/65
