### ISSUE TITLE
Implement dbt snapshot

### ISSUE THREAD

**Issue by findinpath** [starburstdata/dbt-trino#6]
See https://docs.getdbt.com/docs/building-a-dbt-project/snapshots

Possible reference to implement this feature:
https://github.com/dbt-labs/dbt/tree/develop/plugins/postgres

https://github.com/dbt-labs/dbt-spark/blob/master/dbt/include/spark/macros/materializations/snapshot.sql

**Comment by p11o** [comment]
@hovaesco it may be a while until that PR gets merged.  I noticed that other features that use the merge statement have been re-written here (i.e. incremental materialization).  Would it be acceptable to take the same approach here?

**Comment by hovaesco** [comment]
In order to have atomic `merge` incremental strategy, we do require `MERGE` statement support in Trino. My belief is that the only acceptable solution. Do you refer to other incremental strategies?

**Comment by p11o** [comment]
> Do you refer to other incremental strategies?

Hey thanks for taking the time to respond.  Just so I'm on the same page, what do you mean by incremental strategies?

On my end I was referring to how trino overrides this [merge statement](https://github.com/dbt-labs/dbt-core/blob/0d8e061a3d8d726bb10ff767d8f276439cc472b2/core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql#L31) for incremental models.

**Comment by hovaesco** [comment]
https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#about-incremental_strategy

**Comment by mdesmet** [comment]
At this moment dbt_trino only supports append incremental models. See https://github.com/starburstdata/dbt-trino/blob/master/dbt/include/trino/macros/materializations/incremental.sql

We have an [open PR for adding the delete+insert strategy](https://github.com/starburstdata/dbt-trino/pull/62). However to be able to test it, we need to [expand the test setup with iceberg and delta](https://github.com/starburstdata/dbt-trino/pull/70).

I actually concur with @p11o that we could implement this feature using `delete+insert` but still would suggest getting above two PR's in first.

**Comment by retrry** [comment]
Now that both merge and delete+insert is merged there are no blocker for this ticked?

**Comment by findinpath** [comment]
@retrry exactly, `snapshot` will likely land very soon on `dbt-trino`.

**Comment by retrry** [comment]
Could you release dbt-trino 1.2.2 with snapshot support?

**Comment by hovaesco** [comment]
Sure, we'll release it tomorrow, sorry for the delay.

**Comment by hovaesco** [comment]
@retrry here you go https://github.com/starburstdata/dbt-trino/releases/tag/v1.2.2

**Comment by retrry** [comment]
@hovaesco thanks!
